apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service 
spec:
  type: NodePort
  selector:
    app: quiz-app
  ports:
   - port: 80  #service interal port
     targetPort: 80   #container port
     nodePort: 30080   #Accessible from outside the cluster